### ISSUE TITLE
Delete Space

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#573]
Deleting space in the OpenShift.io project should adequately warn the user about what will happen, and provide them options of what parts of their space they might not want to delete and allow them to take action.

From the product manager:
"There are a lot of considerations to be made here, and many equally valid and competing use-cases. We'll need to do some UX research, but, based upon even some back of the napkin use-casing, I feel that we essentially need to offer the user a list of everything which is associated with the Space (pipelines, repos, etc.), each with a checkbox. The checkbox controls "delete this thing, too."

Simple use case A:
I make a new space "foo", use a quickstart, and now have both a "foo" repo and a "foo" pipeline. Then I decide it was a mistake to make it. I likely want to delete everything with one operation.

Simple use case B:
I make a new space "foo" and import an existing "foo" repo. A pipeline is created for me. The I decide it was a mistake to create it. I likely want to delete the space and perhaps the pipeline, but definitely not the repo. (Because it was pre-existing.)

Maybe the logic should be a set of checkboxes, with the checkboxes defaulted to checked (meaning "delete this, too") for those items which were created by OSIO? In other words, in use case A, everything would be defaulted to checked -- Space, Pipeline and Repo. But in use case B, only Space and Pipeline would be checked by default."

Verification criteria:
* Capture use cases and workflows for deleting spaces and review with Catherine Robson, Joshua Wilson, Todd Mancini
* Create wireframes for deleting spaces that match the agreed upon workflows

**Comment by deernano** [comment]
Hi @catrobson @joshuawilson Based on above issue description, I created a workflow to cover the delete space user cases. Please review it
![delete-space-workflow](https://user-images.githubusercontent.com/5396309/29069066-ed3f0886-7c6b-11e7-8018-e0f156abdec3.png)

1.When user wants to delete a space. User need to click the delete space button. A pop up with a list of checkbox items will show. User will pick the items that he wants to delete and then choose yes or no. The only thing is what items need to set as default. As the pictures shows,  If there is only new repo in a certain space, all the items will be default checked. If there is existing repo in the space. the items will be checked expect the code bases. Since code bases might have several different repo. Some are new, others are imported from existing repo. The new repo will be default checked. The imported existing repo will not.
2. We should add delete space function in two places:
     1. In a certain space
     2.In View all spaces
I have one questions:
When user want to delete the space, does he want to delete all the work items?

**Comment by catrobson** [comment]
Can we add workspaces to what we need to clean up with new/existing repos?  We also need to meet with the backend team to talk about this a bit more, so let me set up a meeting around that before we move forward with design.

When you say "existing repo" - do you mean that we're actually looking at GitHub to see if the repo has anything in it beyond what we originally provisioned?

I think at this point by default we would delete all work items, or maybe provide the user a way to copy all work items into another space.  They can't sit as orphans without a space - there is no way to access them.

**Comment by deernano** [comment]
@catrobson  
Ok, lets have a meeting to discuss this with the developer.
Yes. Each workspace corresponds to one repo.  When user deletes a repo, the correspondent workspace will be default checked to delete. I updated the workflow as following:
![delete-space-workflow1](https://user-images.githubusercontent.com/5396309/29111859-909f9862-7d1e-11e7-8378-efe00d83b20b.png)

"existing repo" coming form use case B " I likely want to delete the space and perhaps the pipeline, but definitely not the repo. (Because it was pre-existing.)"  From my understanding, there might be several spaces that is sharing the same repo. In a certain space, the code can based on several repos including the new and existing ( already existing in github) repo.  User could click "add to space" button to add existing repo into the space. See the below screenshot:

![2017-08-09 2 54 54](https://user-images.githubusercontent.com/5396309/29108887-6e6f3424-7d13-11e7-93cc-b3ddc0de363c.png)

![2017-08-09 2 56 26](https://user-images.githubusercontent.com/5396309/29108783-febd0b92-7d12-11e7-91eb-63c6c97d2705.png)

For the "deleting work items" issue,  I provide the workflow that the work items is default checked to delete. If we gonna have a button to move the work items, we can add that function in another issue.

**Comment by deernano** [comment]
@catrobson @joshuawilson 
After the previous meeting. We are agree to have the following workflow: 
1.user click the "delete space" button to delete the space.
2.After clicking the button, the pop up shows. 
3. User read through the content and click "delete" to finish the deleting process.

In the pop up, the following things will be deleted:
Codebases
Workitems
Pipelines
Applitcations
Workspaces
There will be a notification showing user that the the codebases repos on github will not be deleted.

Based on the above workflow, the wireframes are listed below:
1. Entry
There are two entires for "delete space". 
1) In all spaces

![delete-allspace1](https://user-images.githubusercontent.com/5396309/29203233-1a6701c8-7ea2-11e7-9563-6bf2e84683d1.png)

2) In a certain space

![delete-space1 2x](https://user-images.githubusercontent.com/5396309/29203400-1cfb537a-7ea3-11e7-86a8-dd50226be5b5.png)

2. delete space pop up
The delete pop up is using [Patternfly modal widget](https://www.patternfly.org/pattern-library/widgets/#modal) style.

![delete-space2 2x](https://user-images.githubusercontent.com/5396309/29203365-f1f189ba-7ea2-11e7-8287-23236b215ead.png)

1.**Space name** -The title will list the space name in order to let user make sure to delete the correct space.
2.**Notification of repo on github** - The notification is using Patternfly [Inline notification style](http://www.patternfly.org/pattern-library/communication/inline-notifications/). The notification will list the link of the repos on github.
3.**Numbers** - Numbers that showing how many items is going to delete.

**Comment by junezhang** [comment]
@deernano How do you think if changing "Save" to "Delete"?

**Comment by catrobson** [comment]
@deernano this is a pretty serious action to take.  What do you think about following the pattern that @mindreeper2420 put together for cleaning your space, and using a full page rather than a modal?  By going full page we can then return the user to the Account Homepage from this action and it will also be a little less jarring.  https://redhat.invisionapp.com/share/92CZJ7J5S#/screens/247733957

Also, I'd love for us to put the "Delete Space" into a kabob menu on the space dashboard.  Its a rare enough action that having a big button for it on the dashboard feels like clutter for a minimally used action.  What do you think?

**Comment by joshuawilson** [comment]
I don't like the "Delete Space" on the main space dashboard. I do think that having it on the kabob menu would be fine. 
Additionally, we may want to have the user confirm by entering the name of the space they want to delete. This last idea should be discussed, I'm not directing that it must be there.

**Comment by deernano** [comment]
@catrobson @joshuawilson ok I will follow the full space idea.  
On the space dashboard. It's just a demonstration of clicking the "delete" button to delete the space.   @junezhang  is designing the demonstration of the dashboard including the delete button.  So I'm not sure what the button will final looks like.  Currently I just use a screenshot to demonstrate the entry. The design of the button will be solved in this issue https://github.com/fabric8-ui/fabric8-ux/issues/572

**Comment by deernano** [comment]
@catrobson @joshuawilson 
I updated the wireframe to Invision
https://redhat.invisionapp.com/d/#/console/11784393/248643608/preview
I only leave one entry for deleting the space (In view all spaces) at the moment.

![delete-space2 2x](https://user-images.githubusercontent.com/5396309/29304605-8330571e-81c6-11e7-9ebd-339fda84b774.png)

For confirming deleting the space. I have two design that need to discuss with you:
1. Delete space user confirm by checking the checkbox
![delete-space4 2x](https://user-images.githubusercontent.com/5396309/29304627-9cc12924-81c6-11e7-97fe-d17618f1615f.png)
2.Delete space user confirm by entering the name of the space they want to delete
![delete-space11 2x](https://user-images.githubusercontent.com/5396309/29304643-b175bbe6-81c6-11e7-9459-6eccfa966eed.png)
More details, please review the wireframe. Thank you!

**Comment by deernano** [comment]
@catrobson @Essjaysee @mindreeper2420 
Updated the wireframe in Invision. Please review it. Thank you !
https://redhat.invisionapp.com/share/2BD1C1GQY#/248643608_Delete-Space1
