### ISSUE TITLE
Visual: List Row Colors

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#722]
In the design for the new User Settings area, the lists inside of each card have alternating colored rows (mimicking PatternFly’s table styling). Currently, PatternFly does not use alternating color rows for the List View - do we want to standardize on the new design, or keep in line with PatternFly?

**Comment by mindreeper2420** [comment]
Current visual design for User Settings: https://redhat.invisionapp.com/share/GHCW0C3P4

**Comment by mceledonia** [comment]
@mindreeper2420 In this case, since this isn't a fully-fledged list view, I think the alternating rows help a bit with readability and reinforce the idea that these are scrollable areas. I believe the color is #F5F5F5. 

What do you think @bdellasc?

**Comment by mindreeper2420** [comment]
My only concern is that we now have 3 different list views. There is a different list view in a card (on the Dashboards) that does not have the alternating rows, and then our main lists are not alternating rows. Isn't a list view a list view, no matter where it and and what it does?

**Comment by mceledonia** [comment]
That's a good point on having 3 different ones.  I think the both of the card list-views should be the same, but I think the larger list views being different is ok since they take up more space and aren't as tightly packed in as the card list-views. I don't feel too strongly on that though so I could definitely be swayed either way.

**Comment by catrobson** [comment]
Did we make a decision about this the other day in the meeting @bdellasc @mceledonia?

**Comment by bdellasc** [comment]
I agree with @mceledonia RE: any lists on the cards having the same treatment, but that it seems alright for the large list view to be treated differently (strokes between rows, no BG colors).

Just thinking out loud:
- In some cases, we have multiple columns of data which is helpful having the alternating BG colors. The nice thing about having the alternating color rows is that if we end up with wider cards with more columns, they'll be more readable.
- From a "looking across the system" standpoint, do we feel like we'd ever have tables appear in the card views? Or are we thinking we're primarily using these list views? Essentially, we're applying a table treatment (alternating row colors) to a list in these card views.
- Looking at the one mockup of the table in a dashboard card on [PatternFly](http://www.patternfly.org/pattern-library/dashboard/dashboard-layout/), the alternating BG lists don't look any different to me from the table in that mockup, other than the number of columns and the presence of action buttons above the table
- Attached is the same screen with no row BG colors. It feels very stark to me, since this is a screen full of lists.

That do you think?
[
![a-0200-userprofile_noaltcolorrows](https://user-images.githubusercontent.com/17882357/32518137-b53eee1c-c3d6-11e7-9e3b-efea3d60cc29.png)
](url)

**Comment by Essjaysee** [comment]
I will say that the tags (labels, whatever) are clearer and more obvious on the option with the row shading.

**Comment by mindreeper2420** [comment]
I prefer the option with the row shading when inside of a card. As Sj said, things are a lot more obvious with the row shading.

**Comment by mindreeper2420** [comment]
Should this move forward to update the lists inside of cards to be the alternating colors? This would be a nice item to add to the next sprint, if so.

**Comment by catrobson** [comment]
yes, I think we are all in agreement on that direction.
