### ISSUE TITLE
Dev:  Research tree view on ag-grid

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#739]
Understand the amount of effort and flexibility in building a tree into the ag-grid implementation.  Come out of sprint understanding general length of time to deliver this capability on ag-grid to the planner team.

**Comment by dlabrecq** [comment]
I performed another table [evaluation](https://docs.google.com/a/redhat.com/document/d/1wOKNd0zbk8S7rDUNikln-H22w8tmRzzDGO7xOErb1Js/edit?usp=sharing) of the AgGrid and ngx-datatable libraries. I've also created two POCs [AgGrid](https://rawgit.com/dlabrecq/patternfly-ng/ag-grid-dist/dist-demo/#/table) and [ngx-datatable](https://rawgit.com/dlabrecq/patternfly-ng/ngx-datatable-dist/dist-demo/#/table) to study how best to implement new features.

I'm on the fence about which library we should be using. After implementing AgGrid myself, I have some concerns about wrapping it with a new patternfly-ng component. It may be easier to implement new features using the Angular template approach used by ngx-datatable?

Regardless of which library we choose, neither implements a tree or drag-and-drop. If we implement a tree with ngx-datatable, we can potentially contribute that upstream? However, it may be easier to implement drag-and-drop with AgGrid because of its callback support -- need to investigate further.

And if we must fork a repo, and heavily modify the code, that could create a maintenance nightmare. I'd like to avoid that if possible?

Looking at the PatternFly core table, I worked on that for about 4+ months. The initial PR was created September 9th and additional functionality was added over subsequent sprints in October and November -- still submitting bug fix PRs in January. 

In this case, the CSS had already been implemented, so it was pure JavaScript at this point. We only implemented existing datatables.net features; such as, row selection, pagination, toolbar layout, empty state, filter, inline actions, etc.

For PatternFly-NG, the table CSS must be written from scratch because these libraries output div tags. The existing CSS was written to support standard HTML table tags, not the HTML layout generated by AgGrid or ngx-datatable.

For starters, I'm guesstimating 2 weeks to become familiar with the code and implement the tree feature. I'm thinking another 1-2 weeks for drag-and-drop, depending on whether we must modify forked code. Don't know how long it will take to contribute these features to ngx-datatable?

**Comment by dlabrecq** [comment]
Update: The ngx-datatable issues list [drag and drop](https://github.com/swimlane/ngx-datatable/issues/411) as a high effort feature. Although, there is someone actively working on this as of 6 days ago. It appears there may be a PR coming soon?

The ngx-datatable issues list the [tree](https://github.com/swimlane/ngx-datatable/issues/34) as another high effort feature. No one appears to be working on that one.

**Comment by dlabrecq** [comment]
Considering the flexibility provided by ngx-datatable and available feature code, I'd like to propose the following. All these tasks can be performed in parallel, depending on how many devs we're willing to throw at it?

1. Create CSS to skin ngx-datatable for PatternFly.
2. Create a patternfly-ng table component to wrap ngx-datatable.
3. Port the [tree](http://swimlane.github.io/angular-data-table/) feature from angular-data-table and contribute upstream to ngx-datatable.
4. Finish developing the [drag-and-drop](https://plnkr.co/edit/UUxn8x?p=preview) feature as a patternfly-ng directive.
