### ISSUE TITLE
VISUAL:  Icon for status header

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#748]
https://github.com/openshiftio/openshift.io/issues/1363

Determine whether the icon on the header should change as status changes, or if there should be some other indicator to designate when there is a problem.

**Comment by bdellasc** [comment]
Posted first visual pass for the feature on [InVision](https://redhat.invisionapp.com/share/ZFEP5QKXA). Please feel free to comment either here or on the InVision project.

**Comment by bdellasc** [comment]
Reviewed design with @joshuawilson yesterday. He said he'd get it assigned to someone. Just need to mark up the design with a few HEX colors.

**Comment by mishaone** [comment]
Possibly too late, but if the colors don't show up correctly, maybe an alternate like the circle could be filled in white and the check or X could be red or green or just grey for "wait". This would make the colors show up. My intention with the issue was to have a way to see the tenant status that is obvious at a quick look. A green and red color indicator fits that bill.

**Comment by bdellasc** [comment]
Chatted with dev on Mattermost this afternoon and updated the flow with additional information they needed to implement. They'l reach out tomorrow with any additional questions.
