### ISSUE TITLE
HTML/CSS: Create application wizard

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#803]
HTML/CSS implementation of the application wizard.  The goal should be to get the broad elements in place during this sprint so that the JS developers can start to stub out what would be needed at the service layer in the next sprint.

Visual design of the application wizard is happening here:  https://github.com/fabric8-ui/fabric8-ux/issues/790

**Comment by mindreeper2420** [comment]
Created a demo page as part of the ngx-launcher repo, based off of Dana's demo app work. Added the first 2 sections according to the wireframes and visuals designs. Scrollspy needs to be added, in order to track where the user is in the process, and match that to the navigation item (highlighting and smooth scrolling).

Future updates to the demo will include the final 3 sections, as designed, as well as visual improvements and animations.

**Comment by mindreeper2420** [comment]
All sections have been hard coded and included in the demo page. Working with Brian and Laura on layout variations from original designs and animations/visuals to improve user experience as they progress through the launcher. 

Additional items to complete included finalizing component breakout, adding variables to styles for different quantities of steps and final flow, based on selections.

**Comment by mindreeper2420** [comment]
Closing this story and creating a new one (https://github.com/fabric8-ui/fabric8-ux/issues/836) until additional decisions are made on keeping this wizard format vs using the standard PatternFly wizard.
