### ISSUE TITLE
DEV: Hierarchical areas

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#835]
Change areas list view to a hierarchical list view that shows parent/child relationships.  Ideally add a filter bar that allows me to keyword search the areas.  All other elements can stay the same, or you can work with one of the designers for some tidying up of the page if there needs to be discussion on where filter bar, title, and add belong together.

**Comment by dlabrecq** [comment]
I replaced the list with a tree list, added a toolbar with filter/sort/add controls and set the toggles to expand by default. Unfortunately, the APIs do not provide descriptions, nor any way to delete an area, or change its name.

**Full tree**
![tree](https://user-images.githubusercontent.com/17481322/37368341-563b6fc6-26dc-11e8-924c-60f379c02bfc.png)

I wasn't quite certain how filtering should behave for a tree list, but believe the remaining items should still represent a hierarchy -- minus the items that were filtered-out. The problem is that remaining items may no longer have a direct parent (it was filtered-out), so its closest ancestor is used to represent the hierarchy. This is shown by the screen shots below.

**Filter "area"**
![filter-area](https://user-images.githubusercontent.com/17481322/37368377-7478b2e6-26dc-11e8-9042-77ce08b39545.png)

Here only items matching "area" are shown. This still represents a hierarchy, but "area1a" is not the parent of "area1c" -- its an ancestor. That's because items beginning with "test" have been filtered-out.

**Filter "test"**
![fiter-test](https://user-images.githubusercontent.com/17481322/37368368-6c24236e-26dc-11e8-949a-373900b9e2fc.png)

**Comment by dlabrecq** [comment]
Created a PR with changes here: https://github.com/fabric8-ui/fabric8-ui/pull/2638
