### ISSUE TITLE
HTML/CSS: Space Dashboard Updates

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ux#925]
Update the Space Dashboards to match the new designs from UXD:
https://redhat.invisionapp.com/share/DQFLCG4G9YK

Visual Design Story https://github.com/fabric8-ui/fabric8-ux/issues/883

Verification Criteria:
- [x] Review with Michael D.
- [x] Review with UXD during Design Review session
- [ ] Review with fabric8-ui dev leads

**Comment by mindreeper2420** [comment]
![osio_spacedashboard_new](https://user-images.githubusercontent.com/4032718/37538287-9155fd50-2926-11e8-8440-ddfc87a69ba3.png)

**Comment by mindreeper2420** [comment]
Implementation of the Feature Flag switcher is blocked due to issues with prod-preview after the migration. I'll keep track of any stability improvements and remove the blocker label when possible.

**Comment by mindreeper2420** [comment]
The prod-preview environment is still too unstable to use. This issue will remain blocked until that environment is running properly.

**Comment by mindreeper2420** [comment]
PR filed - closing this issue

**Comment by andrewazores** [comment]
@mindreeper2420 not sure if there's a better place to ask, but is the EnvironmentWidget being permanently removed from the new Analyze dashboard? I see that it's present but commented out in the new dashboard template. I ask because that component is currently a consumer of the DeploymentsService, which we're refactoring to be internal to the Deployments area, and have a different service (DeploymentApiService) exported which the EnvironmentWidget should consume instead. Whether this component is obsoleted and will be removed from the upcoming redesigned dashboard or will live on in a future update will influence how I refactor the DeploymentsService, DeploymentApiService, and EnvironmentWidget.

**Comment by AdamJ** [comment]
@andrewazores yes, the EnvironmentWidget is being removed from the Analyze Dashboard. Part of the Environments area of OSIO are being combined into the new Applications widget, in order to provide users a better overview of their setup.

@dlabrecq is currently working on connecting the Space Dashboard, so he would the best to speak with regarding the full implementation of the Applications widget.

**Comment by dlabrecq** [comment]
I'm planning on reusing the code found in the deployments details. I see that DeploymentDetailsComponent currently uses DeploymentsService. Will you refactor that to use DeploymentApiService?

**Comment by andrewazores** [comment]
@dlabrecq DeploymentDetailsComponent will continue using the DeploymentsService, since that component is an "internal" Deployments area consumer. An external consumer like the Applications widget should not consume the DeploymentsService, and should instead use the DeploymentApiService.

**Comment by andrewazores** [comment]
@mindreeper2420 do you have a timeline for when the new dashboard will become the default for all users, ie when the EnvironmentWidget can be removed? If it's still going to stick around for some time then I'll move ahead with my small patch to decouple it from the DeploymentsService. If it's only a matter of days then I'll simply wait for it to be removed, or help remove it.

**Comment by dlabrecq** [comment]
I don't believe we will remove the EnvironmentWidget as part of these changes. Although we won't show it in the new dashboard, I can see it being useful at some point in the future? For example, we talked about making the dashboard customizable, where users could swap out widgets.

**Comment by andrewazores** [comment]
Okay, in that case I will move forward with refactoring the widget to consume the new service. Thanks for the info.
